baseURL = "https://blog.k33experts.com"
title = "k33 Blog"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = ""
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "[k33 Experts](https://k33experts.com/en/)."
startYear = "2018"
suffix = "Please see our [legal note](/en/blog/info/legal) and [privacy statement](/en/blog/info/privacy). Built with [Hugo](https://gohugo.io/) and the [Minimo theme](https://themes.gohugo.io/minimo/)."

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#f0326bff"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = []
homepage = ["recent_posts"]
sidebar = ["about","search", "recent_posts", "taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "https://twitter.com/k33experts" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = "contact@example.com"
facebook = ""
github = "https://github.com/05dirnbe"
gitlab = ""
instagram = ""
linkedin = "https://www.linkedin.com/in/michael-dirnberger-0ba1b0171/"
twitter = "https://twitter.com/k33experts"
telegram = ""
google_scholar = ""
youtube = ""

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "MunifTanjim"
repository = "minimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
  name = "Hire me!"
  weight = -10
  identifier = "k33"
  url = "https://k33experts.com/en/service/"

[[menu.main]]
  name    = "courses"
  weight  = -20
  identifier = "courses"
  url     = "https://k33-academy.thinkific.com/courses"

[[menu.main]]
  name    = "Subscribe"
  weight  = -15
  identifier = "subscribe"
  url     = "https://eepurl.com/goqHb5"


[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[Languages.en.cookies]
    dismiss = "I Agree."
    message = "We use cookies to offer you a better experience and to gain insight into site traffic. By continuing to use this website, you consent to the use of cookies as explained in our "
    href = "info/privacy"
    link = "privacy policy."

[Languages.en.params.contact]
  firma = "k33 Experts e.U."
  name = "Michael Dirnberger"
  street = "Mühlgasse 30"
  town = "8020 Graz"
  country = "Austria"
  address = "Mühlgasse 30, 8020 Graz, Austria"
  phone   = "0043 670 4081560"
  fax     = ""
  mail = "contact@k33experts.com"
  purpose = "Services in automatic data processing and information technology"
  uid = "VAT"
  companynumber = "Firmenbuchnummer"
  companycourt = "Firmenbuchgericht"
  memberships = "WKÖ"
  regulation = "Gewerbeordnung"
  regulator = "Magistrat Graz"
  content = "Information on modern technologies centering around the topic of graphs."
